# Используем конкретную свежую версию Rust, чтобы обеспечить совместимость инструментов
image: rust:1.88

stages:
  - build

build_blockchain:
  stage: build
  
  script:
    # 1. Устанавливаем все системные зависимости
    - apt-get update && apt-get install -y libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang protobuf-compiler
    
    # 2. Запускаем скрипт сборки
    - ./scripts/cargo-install-all.sh .
    
  artifacts:
    name: "solana-binaries"
    paths:
      - /builds/nuah/n-dollar/NUAH-Blockchain/bin/ # Изменим путь на более корректный
    expire_in: 1 week